/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package RealState_Admin;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Minhajul Abedin
 */

public class AdminFrontFrame extends javax.swing.JFrame {
    
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;
    /**
     * Creates new form AdminFrontPage
     */
    String adminID=null;
    String username=null;
    public AdminFrontFrame() {
        initComponents();
    }
    public AdminFrontFrame(String userN,String userid) throws SQLException{
        this();
        adminID=userid;
        username=userN;
        aidField.setText(adminID);
        usnField.setText(username);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usnField = new java.awt.Label();
        aidField = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        lgoutT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        enquiriesB = new javax.swing.JButton();
        pdT = new javax.swing.JButton();
        userDetailsB = new javax.swing.JButton();
        pdT1 = new javax.swing.JButton();
        srbT = new javax.swing.JTextField();
        srT = new javax.swing.JButton();
        slocT = new javax.swing.JCheckBox();
        sszOT = new javax.swing.JCheckBox();
        sprT = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Admin Id:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Username:");

        usnField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usnField.setText("U_name");

        aidField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        aidField.setText("A_id");

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 2, 36)); // NOI18N
        jLabel3.setText("RealSTate.co");

        lgoutT.setBackground(new java.awt.Color(255, 204, 204));
        lgoutT.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lgoutT.setText("Log out");
        lgoutT.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 204), new java.awt.Color(255, 204, 51), new java.awt.Color(153, 255, 204), new java.awt.Color(255, 218, 124)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 255, 153), new java.awt.Color(204, 204, 255), new java.awt.Color(255, 255, 204))));
        lgoutT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgoutTActionPerformed(evt);
            }
        });

        jLabel9.setText("Minhajul Abedin:-18301224");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 612, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usnField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aidField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lgoutT))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addComponent(lgoutT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        enquiriesB.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enquiriesB.setText("Enqueries");
        enquiriesB.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 186, 103), new java.awt.Color(0, 255, 153), new java.awt.Color(51, 255, 51), new java.awt.Color(255, 218, 124)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204))));
        enquiriesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquiriesBActionPerformed(evt);
            }
        });

        pdT.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        pdT.setText("Properties(N/A)");
        pdT.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 186, 103), new java.awt.Color(0, 255, 153), new java.awt.Color(51, 255, 51), new java.awt.Color(255, 218, 124)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204))));
        pdT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdTActionPerformed(evt);
            }
        });

        userDetailsB.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        userDetailsB.setText("User Details");
        userDetailsB.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 186, 103), new java.awt.Color(0, 255, 153), new java.awt.Color(51, 255, 51), new java.awt.Color(255, 218, 124)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204))));
        userDetailsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDetailsBActionPerformed(evt);
            }
        });

        pdT1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        pdT1.setText("New Admin(N/A)");
        pdT1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 186, 103), new java.awt.Color(0, 255, 153), new java.awt.Color(51, 255, 51), new java.awt.Color(255, 218, 124)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204))));
        pdT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdT1ActionPerformed(evt);
            }
        });

        srbT.setText("Not Available");
        srbT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srbTActionPerformed(evt);
            }
        });

        srT.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        srT.setText("Search(N/A)");
        srT.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 204), new java.awt.Color(255, 204, 51), new java.awt.Color(153, 255, 204), new java.awt.Color(255, 218, 124)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 255, 153), new java.awt.Color(204, 204, 255), new java.awt.Color(255, 255, 204))));
        srT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srTActionPerformed(evt);
            }
        });

        slocT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        slocT.setText("Location");

        sszOT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sszOT.setText("Size");

        sprT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sprT.setText("Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(345, 345, 345)
                            .addComponent(enquiriesB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(sszOT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sprT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(slocT))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(srbT, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(srT)))
                    .addComponent(userDetailsB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pdT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(pdT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srbT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sszOT)
                    .addComponent(sprT)
                    .addComponent(slocT))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userDetailsB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquiriesB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdT, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdT1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Go to the enquiry page if clicked in enquiry button.
    private void enquiriesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquiriesBActionPerformed
        try {
            AdminEnquiryFrame aef=new AdminEnquiryFrame(username,adminID);
            aef.setVisible(true);
            aef.setLocationRelativeTo(this);
            this.setVisible(false);
            //dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AdminFrontFrame.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_enquiriesBActionPerformed
    
    private void pdTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdTActionPerformed
        
    }//GEN-LAST:event_pdTActionPerformed
    // Goes to the user detail page to when clicked user detail button.
    private void userDetailsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDetailsBActionPerformed
        try {
            AdminUserDetailFrame audf=new AdminUserDetailFrame(username,adminID);
            audf.setVisible(true);
            audf.setLocationRelativeTo(this);
            this.setVisible(false);
            //dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AdminFrontFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_userDetailsBActionPerformed
    
    private void pdT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdT1ActionPerformed
        
    }//GEN-LAST:event_pdT1ActionPerformed
    
    private void srbTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srbTActionPerformed
        
    }//GEN-LAST:event_srbTActionPerformed
    
    private void srTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srTActionPerformed
        
    }//GEN-LAST:event_srTActionPerformed
    //logout performed if logout button clicked.
    private void lgoutTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgoutTActionPerformed
        AdminLoginFrame alf = new AdminLoginFrame();
        alf.setVisible(true);
        alf.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_lgoutTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame= new AdminFrontFrame();
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label aidField;
    private javax.swing.JButton enquiriesB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lgoutT;
    private javax.swing.JButton pdT;
    private javax.swing.JButton pdT1;
    private javax.swing.JCheckBox slocT;
    private javax.swing.JCheckBox sprT;
    private javax.swing.JButton srT;
    private javax.swing.JTextField srbT;
    private javax.swing.JCheckBox sszOT;
    private javax.swing.JButton userDetailsB;
    private java.awt.Label usnField;
    // End of variables declaration//GEN-END:variables
}
